---
name: Code style check

on:
  workflow_dispatch:
  push:
    branches:
      - master
      - develop
    tags:
      - '**'
  pull_request:
    paths-ignore:
      - '.github/workflows/*.yml'
      - 'tests/*'

jobs:
  job_lint:
    name: Linter using the reusable workflow
    uses: LedgerHQ/ledger-app-workflows/.github/workflows/reusable_lint.yml@v1
    with:
      source: 'src'
      extensions: 'h,c'
      version: 11

  misspell:
    name: Check misspellings
    runs-on: ubuntu-latest
    steps:
    - name: Clone
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Check misspellings
      uses: codespell-project/actions-codespell@v1
      with:
        builtin: clear,rare
        check_filenames: true
